[tool.ruff]
line-length = 100
target-version = "py311"
force-exclude = true
exclude = [
  ".git",
  "__pycache__",
  ".venv",
  ".venv*",
  "build",
  "dist",
  # Stage 2 pending files remain excluded until C hygiene verified in CI
  "src/risk/risk_manager_impl.py",
  "src/integration/component_integrator.py",
  "src/sensory/organs/dimensions/anomaly_dimension.py",
  "src/thinking/analysis/market_analyzer.py",
  "src/thinking/phase3_orchestrator.py",
]

[tool.ruff.lint.isort]
known-first-party = ["src"]

[tool.ruff.lint.per-file-ignores]
"scripts/backtest_report.py" = ["F401","F811"]
"src/genome/__init__.py" = ["F403","F405"]
"src/evolution/__init__.py" = ["F403","F405"]
"src/evolution/engine/__init__.py" = ["F403","F405"]
"src/thinking/__init__.py" = ["F403","F405"]
# Targeted ignores for lazy re-exports and namespace preservation
"src/domain/__init__.py" = ["F401"]
"src/sensory/models/__init__.py" = ["F401"]
"src/ui/ui_manager.py" = ["F401"]

"src/thinking/thinking_manager.py" = ["I001"]

# New targeted ignores to keep CI green while we refactor
"main.py" = ["I001","F401"]  # import order noise; top-level integrity check moved inside main()
"src/core/base.py" = ["I001"]  # complex TYPE_CHECKING import blocks
"src/sensory/organs/dimensions/pattern_engine.py" = ["I001"]  # large grouped imports; refactor tracked in M2
"src/sensory/tests/test_integration.py" = ["I001"]  # legacy test import ordering
"src/market_intelligence/dimensions/enhanced_how_dimension.py" = ["F401"]
"src/market_intelligence/dimensions/enhanced_what_dimension.py" = ["F401"]
[tool.ruff.lint]
# Keep CI green with a minimal, safety-focused rule set.
# Adopt full style rules incrementally in future PRs.
select = ["E9", "F63", "F7", "F82"]
ignore = []

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["src"]
src_paths = ["src", "tests", "stubs"]

# mypy configuration is managed via mypy.ini to support a transitional, per-package strictness rollout.
# This pyproject [tool.mypy] section is intentionally omitted to avoid conflicting, repo-wide strict settings.
[tool.coverage.run]
branch = true
relative_files = true
source = ["src"]
include = [
  "src/core/**",
  "src/trading/execution/**",
  "src/trading/models/**",
  "src/operational/metrics.py"
]

[tool.coverage.report]
show_missing = true
skip_empty = true
precision = 2
fail_under = 70
include = [
  "src/trading/execution/execution_model.py",
  "src/trading/models/position.py",
  "src/trading/models/trade.py",
  "src/trading/models/__init__.py",
  "src/core/interfaces/__init__.py",
  "src/core/sensory_organ.py",
  "src/operational/metrics.py",
  "src/operational/mock_fix.py",
  "src/data_foundation/config/execution_config.py",
  "src/data_foundation/config/risk_portfolio_config.py",
  "src/data_foundation/config/sizing_config.py",
  "src/data_foundation/config/why_config.py",
  "src/sensory/dimensions/why/yield_signal.py"
]
