[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [
  ".git",
  "__pycache__",
  "build",
  "dist",
  # Stage 2 pending files remain excluded until C hygiene verified in CI
  "src/risk/risk_manager_impl.py",
  "src/integration/component_integrator.py",
  "src/sensory/organs/dimensions/anomaly_dimension.py",
  "src/thinking/analysis/market_analyzer.py",
  "src/thinking/phase3_orchestrator.py",
]

[tool.ruff.lint.isort]
known-first-party = ["src"]

[tool.ruff.lint.per-file-ignores]
"scripts/backtest_report.py" = ["F401","F811"]
"src/genome/__init__.py" = ["F403","F405"]
"src/evolution/__init__.py" = ["F403","F405"]
"src/evolution/engine/__init__.py" = ["F403","F405"]
"src/thinking/__init__.py" = ["F403","F405"]

[tool.ruff.lint]
# Keep CI green with a minimal, safety-focused rule set.
# Adopt full style rules incrementally in future PRs.
select = ["E9", "F63", "F7", "F82"]
ignore = []

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
ignore_missing_imports = false
disallow_untyped_defs = false
check_untyped_defs = false
no_strict_optional = true
show_error_codes = true



