[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [
  ".git",
  "__pycache__",
  "build",
  "dist",
  # Stage 2 pending files remain excluded until C hygiene verified in CI
  "src/risk/risk_manager_impl.py",
  "src/integration/component_integrator.py",
  "src/sensory/organs/dimensions/anomaly_dimension.py",
  "src/thinking/analysis/market_analyzer.py",
  "src/thinking/phase3_orchestrator.py",
]

[tool.ruff.lint.isort]
known-first-party = ["src"]

[tool.ruff.lint.per-file-ignores]
"scripts/backtest_report.py" = ["F401","F811"]
"src/genome/__init__.py" = ["F403","F405"]
"src/evolution/__init__.py" = ["F403","F405"]
"src/evolution/engine/__init__.py" = ["F403","F405"]
"src/thinking/__init__.py" = ["F403","F405"]
# Targeted ignores for lazy re-exports and namespace preservation
"src/core.py" = ["E402"]
"src/data_foundation/ingest/fred_calendar.py" = ["E402"]
"src/data_foundation/replay/multidim_replayer.py" = ["E402"]
"src/data_integration/__init__.py" = ["E402"]
"src/domain/__init__.py" = ["F401"]
"src/intelligence/predictive_modeling.py" = ["E402"]
"src/intelligence/red_team_ai.py" = ["E402"]
"src/intelligence/sentient_adaptation.py" = ["E402"]
"src/operational/md_capture.py" = ["E402"]
"src/performance/__init__.py" = ["E402"]
"src/phase2d_integration_validator.py" = ["E402"]
"src/sensory/dimensions/why/yield_signal.py" = ["E402"]
"src/sensory/models/__init__.py" = ["F401","E402"]
"src/sensory/organs/dimensions/base_organ.py" = ["E402"]
"src/sensory/organs/dimensions/utils.py" = ["E402"]
"src/thinking/adversarial/market_gan.py" = ["E402"]
"src/thinking/prediction/predictive_modeler.py" = ["E402"]
"src/trading/execution/execution_model.py" = ["E402"]
"src/trading/models.py" = ["E402"]
"src/trading/portfolio/real_portfolio_monitor.py" = ["E402"]
"src/trading/strategies/order_book_analyzer.py" = ["E402"]
"src/trading/trading_manager.py" = ["E402"]
"src/ui/ui_manager.py" = ["F401"]
"tests/current/test_fix_lifecycle.py" = ["E402"]

"src/domain/models.py" = ["E402"]
"src/intelligence/adversarial_training.py" = ["E402"]
"src/intelligence/competitive_intelligence.py" = ["E402"]
"src/operational/mock_fix.py" = ["E402"]
[tool.ruff.lint]
# Keep CI green with a minimal, safety-focused rule set.
# Adopt full style rules incrementally in future PRs.
select = ["E9", "F63", "F7", "F82"]
ignore = []

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
ignore_missing_imports = false
disallow_untyped_defs = false
check_untyped_defs = false
no_strict_optional = true
show_error_codes = true
# Narrow initial type-checking scope to critical packages; exclude high-churn/experimental areas.
exclude = '''
^(src/(thinking|intelligence|validation|ecosystem|genome|integration|operational|performance|data_integration|ui|simulation|sentient|portfolio|domain|trading|sensory)/.*)|
^(src/data_foundation/(ingest|persist|replay)/.*)|
^(src/phase2d_.*)
'''




[[tool.mypy.overrides]]
module = [
  "src.validation.*",
  "src.ecosystem.*",
  "src.genome.*",
  "src.integration.*",
  "src.operational.*",
  "src.performance.*",
  "src.data_integration.*",
  "src.ui.*",
  "src.simulation.*",
  "src.sentient.*",
  "src.portfolio.*",
  "src.domain.*",
  "src.trading.*",
  "src.sensory.*",
  "src.evolution.*",
  "src.risk.*",
  "src.core.*",
  "src.governance.*",
  "src.data_foundation.config.*",
  "src.phase2d_integration_validator",
  "src.pnl"
]
ignore_errors = true
