[tool.ruff]
line-length = 100
[tool.ruff.lint.isort]
known-first-party = ["src"]

[tool.ruff.lint.per-file-ignores]
"scripts/backtest_report.py" = ["F401","F811"]

[tool.ruff.lint]
select = ["E","F","I"]
ignore = []
target-version = "py311"
exclude = [
  ".git",
  "__pycache__",
  "build",
  "dist",
]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_defs = false
check_untyped_defs = false
no_strict_optional = true
show_error_codes = true


