[tool.ruff]
line-length = 100
target-version = "py311"
force-exclude = true
exclude = [
  ".git",
  "__pycache__",
  ".venv",
  ".venv*",
  "build",
  "dist",
  # Stage 2 pending files remain excluded until C hygiene verified in CI
  "src/risk/risk_manager_impl.py",
  "src/integration/component_integrator.py",
  "src/sensory/organs/dimensions/anomaly_dimension.py",
  "src/thinking/analysis/market_analyzer.py",
  "src/thinking/phase3_orchestrator.py",
]

[tool.ruff.lint.isort]
known-first-party = ["src"]

[tool.ruff.lint.per-file-ignores]
"scripts/backtest_report.py" = ["F401","F811"]
"src/genome/__init__.py" = ["F403","F405"]
"src/evolution/__init__.py" = ["F403","F405"]
"src/evolution/engine/__init__.py" = ["F403","F405"]
"src/thinking/__init__.py" = ["F403","F405"]
# Targeted ignores for lazy re-exports and namespace preservation
"src/domain/__init__.py" = ["F401"]
"src/sensory/models/__init__.py" = ["F401"]
"src/ui/ui_manager.py" = ["F401"]

"src/thinking/thinking_manager.py" = ["I001"]

# New targeted ignores to keep CI green while we refactor
"main.py" = ["I001","F401"]  # import order noise; top-level integrity check moved inside main()
"src/core/base.py" = ["I001"]  # complex TYPE_CHECKING import blocks
"src/sensory/organs/dimensions/pattern_engine.py" = ["I001"]  # large grouped imports; refactor tracked in M2
"src/sensory/tests/test_integration.py" = ["I001"]  # legacy test import ordering
"src/market_intelligence/dimensions/enhanced_how_dimension.py" = ["F401"]
"src/market_intelligence/dimensions/enhanced_what_dimension.py" = ["F401"]
[tool.ruff.lint]
# Keep CI green with a minimal, safety-focused rule set.
# Adopt full style rules incrementally in future PRs.
# Unified with CI selection to avoid drift.
select = ["E9","F63","F7","F82","E402","F401","I001","F403","F405"]
ignore = []

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_defs = false
check_untyped_defs = false
no_strict_optional = true
show_error_codes = true
# Narrow initial type-checking scope to critical packages; exclude high-churn/experimental areas.
exclude = '''
^(src/(thinking|intelligence|validation|ecosystem|genome|integration|operational|performance|data_integration|ui|simulation|sentient|portfolio|domain|trading|sensory)/.*)|
^(src/data_foundation/(ingest|persist|replay)/.*)|
^(src/phase2d_.*)
'''




[[tool.mypy.overrides]]
module = [
  "src.validation.*",
  "src.ecosystem.*",
  "src.genome.*",
  "src.integration.*",
  "src.operational.*",
  "src.performance.*",
  "src.data_integration.*",
  "src.ui.*",
  "src.simulation.*",
  "src.sentient.*",
  "src.portfolio.*",
  "src.domain.*",
  "src.trading.*",
  "src.sensory.*",
  "src.evolution.*",
  "src.risk.*",
  "src.core.*",
  "src.governance.*",
  "src.data_foundation.config.*",
  "src.phase2d_integration_validator",
  "src.pnl"
]
ignore_errors = true

[tool.coverage.run]
branch = true
relative_files = true
source = ["src"]
include = [
  "src/core/**",
  "src/trading/execution/**",
  "src/trading/models/**",
  "src/operational/metrics.py"
]

[tool.coverage.report]
show_missing = true
skip_empty = true
precision = 2
fail_under = 85
include = [
    "src/trading/execution/execution_model.py",
    "src/trading/models/position.py",
    "src/trading/models/trade.py",
    "src/trading/models/__init__.py",
    "src/core/interfaces.py",
    "src/core/sensory_organ.py",
    "src/operational/metrics.py",
    "src/operational/mock_fix.py",
    "src/data_foundation/config/execution_config.py",
    "src/data_foundation/config/risk_portfolio_config.py",
    "src/data_foundation/config/sizing_config.py",
    "src/data_foundation/config/why_config.py",
    "src/sensory/dimensions/why/yield_signal.py"
]
