[tool.mypy]
python_version = "3.11"
mypy_path = ["stubs/src", "stubs"]
namespace_packages = true
explicit_package_bases = true
packages = ["src"]
ignore_missing_imports = true
allow_redefinition = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
no_implicit_optional = false
disallow_any_generics = false
check_untyped_defs = false
warn_unused_ignores = false
warn_redundant_casts = false
warn_return_any = false
warn_unreachable = false
strict_equality = false
show_error_codes = true
pretty = true
plugins = ["pydantic.mypy"]
follow_imports = "normal"
[tool.coverage.run]
branch = true
relative_files = true
source = ["src"]
include = [
  "src/core/**",
  "src/trading/execution/**",
  "src/trading/models/**",
  "src/operational/metrics.py"
]

[tool.coverage.report]
show_missing = true
skip_empty = true
precision = 2
fail_under = 70
include = [
  "src/trading/execution/execution_model.py",
  "src/trading/models/position.py",
  "src/trading/models/trade.py",
  "src/trading/models/__init__.py",
  "src/core/interfaces.py",
  "src/core/sensory_organ.py",
  "src/operational/metrics.py",
  "src/operational/mock_fix.py",
  "src/data_foundation/config/execution_config.py",
  "src/data_foundation/config/risk_portfolio_config.py",
  "src/data_foundation/config/sizing_config.py",
  "src/data_foundation/config/why_config.py",
  "src/sensory/dimensions/why/yield_signal.py"
]
