apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: emp-system
generators:
  - secret-generator.yaml
resources:
  - ../../base
patches:
  - path: patch-configmap.yaml
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
nameSuffix: -prod
commonLabels:
  env: production
images:
  - name: ghcr.io/emp/emp-app
    newTag: stable
