apiVersion: batch/v1
kind: CronJob
metadata:
  name: emp-nightly-replay
  namespace: emp-system
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nightly-replay
              image: ghcr.io/emp/emp-app:stable
              args:
                - --log-level
                - INFO
                - --run-root
                - /app/artifacts/nightly_replay
                - --approvals
                - risk-ops
