from typing import Iterable, Mapping, Sequence, Tuple, List, Optional, Union

# Minimal duckdb typing stubs sufficient for this codebase’s usage.
# These are intentionally narrow and avoid Any to comply with strict mypy settings.

class DuckDBPyConnection:
    def execute(self, sql: str, parameters: object | None = ...) -> "DuckDBPyConnection": ...
    def fetchall(self) -> list[tuple[object, ...]]: ...
    def dataframe(self) -> object: ...

class DuckResult:
    def to_df(self) -> object: ...

def connect(database: str | None = ...) -> DuckDBPyConnection: ...
def query(sql: str) -> DuckResult: ...