class FixMessage:
    def __init__(self) -> None: ...
    def append_pair(self, tag: int, value: str) -> None: ...
    def encode(self) -> bytes: ...
    def decode(self, data: bytes) -> None: ...

class FixParser:
    def __init__(self) -> None: ...
    def append(self, data: bytes) -> None: ...
    def append_buffer(self, data: bytes) -> None: ...
    def get_message(self) -> FixMessage | None: ...
