from __future__ import annotations
from typing import Any, Callable, Dict, TypeVar

T = TypeVar("T", bound=Callable[..., Any])

def model_validator(*args: Any, **kwargs: Any) -> Callable[[T], T]: ...
def validator(*args: Any, **kwargs: Any) -> Callable[[T], T]: ...
def Field(default: Any = ..., **kwargs: Any) -> Any: ...

class BaseModel:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def dict(self, *args: Any, **kwargs: Any) -> Dict[str, Any]: ...
    def json(self, *args: Any, **kwargs: Any) -> str: ...