# IC Markets cTrader Configuration (Legacy)
#
# This file contains OAuth 2.0 credentials for the deprecated cTrader OpenAPI
# integration. The FIX-only [Integration Policy](../../docs/policies/integration_policy.md)
# blocks this flow in active builds; keep this file for archival reference only.
# 
# IMPORTANT: Never commit real credentials to version control!
# Use environment variables or secure credential management in production.

# OAuth 2.0 Configuration
oauth:
  # Demo Account (for testing)
  demo:
    client_id: "${CTRADER_DEMO_CLIENT_ID}"
    client_secret: "${CTRADER_DEMO_CLIENT_SECRET}"
    redirect_uri: "http://localhost:8080/callback"
    host: "demo.ctrader.com"
    
  # Live Account (for production)
  live:
    client_id: "${CTRADER_LIVE_CLIENT_ID}"
    client_secret: "${CTRADER_LIVE_CLIENT_SECRET}"
    redirect_uri: "http://localhost:8080/callback"
    host: "live.ctrader.com"

# Trading Configuration
trading:
  # Default account type (demo/live)
  default_account: "demo"
  
  # Risk Management
  max_positions: 5
  max_risk_per_trade: 0.02  # 2% per trade
  max_daily_loss: 0.05      # 5% daily loss limit
  
  # Position Sizing
  default_volume: 0.01      # Default lot size
  min_volume: 0.01          # Minimum lot size
  max_volume: 1.0           # Maximum lot size
  
  # Order Management
  default_stop_loss_pips: 50
  default_take_profit_pips: 100
  enable_trailing_stop: true
  trailing_stop_pips: 20

# Market Data Configuration
market_data:
  # Symbols to subscribe to
  symbols:
    - "EURUSD"
    - "GBPUSD"
    - "USDJPY"
    - "USDCHF"
    - "AUDUSD"
    - "USDCAD"
  
  # Update frequency (seconds)
  update_interval: 1
  
  # Data storage
  store_ticks: true
  max_ticks_per_symbol: 10000

# Connection Settings
connection:
  timeout: 30
  retry_attempts: 3
  retry_delay: 5
  heartbeat_interval: 30

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/ctrader.log"
  max_size: "10MB"
  backup_count: 5

# Development Settings
development:
  # Use mock interface for testing (set to false for real trading)
  use_mock: true
  
  # Enable detailed logging
  verbose_logging: true
  
  # Test mode (no real orders)
  test_mode: true

# Example configuration for testing (replace with real values)
# oauth:
#   demo:
#     client_id: "your_demo_client_id"
#     client_secret: "your_demo_client_secret"
#     redirect_uri: "http://localhost:8080/callback"
#     host: "demo.ctrader.com" 