from typing import Any

class Index:
    d: int
    is_trained: bool
    ntotal: int
    def add(self, x: object) -> None: ...
    def search(self, x: object, k: int) -> tuple[object, object]: ...
    def reset(self) -> None: ...
    def train(self, x: object) -> None: ...

class IndexFlatL2(Index):
    def __init__(self, d: int) -> None: ...

class IndexFlatIP(Index):
    def __init__(self, d: int) -> None: ...

class IndexIDMap(Index):
    def __init__(self, index: Index) -> None: ...
    def add_with_ids(self, x: object, ids: object) -> None: ...

def read_index(path: str) -> Index: ...
def write_index(index: Index, path: str) -> None: ...
