# EMP Ultimate Architecture v1.1 - Prometheus Configuration
# Metrics collection and monitoring setup

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: emp-production
    environment: production

rule_files:
  - "emp_rules.yml"

scrape_configs:
  # Prometheus scrapes itself so the UI exposes runtime health metrics.
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  # EMP runtime metrics exposed via start_metrics_server /metrics endpoint.
  - job_name: 'emp-runtime'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    static_configs:
      - targets: ['emp-engine:8081']

  # Redis exporter (oliver006/redis_exporter) proxying Redis stats.
  - job_name: 'redis-exporter'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['redis-exporter:9121']

  # TimescaleDB/PostgreSQL exporter (prometheuscommunity/postgres-exporter).
  - job_name: 'timescaledb-exporter'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['timescaledb-exporter:9187']

  # Kafka exporter (danielqsj/kafka-exporter) publishing broker metrics.
  - job_name: 'kafka-exporter'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['kafka-exporter:9308']

  # Additional exporters (e.g. node-exporter) can be registered via file_sd or relabel configs.
