# EMP Ultimate Architecture v1.1 - Kubernetes Deployment
# Production deployment configuration

apiVersion: v1
kind: Namespace
metadata:
  name: emp-system
  labels:
    name: emp-system
    app: emp
    version: "1.1.0"

---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: emp-config
  namespace: emp-system
data:
  EMP_ENVIRONMENT: "production"
  EMP_SYSTEM_VERSION: "1.1.0"
  LOG_LEVEL: "INFO"
  REDIS_HOST: "emp-redis"
  POSTGRES_HOST: "emp-postgres"
  NATS_HOST: "emp-nats"

---
# Secret for sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: emp-secrets
  namespace: emp-system
type: Opaque
data:
  # Base64 encoded secrets
  POSTGRES_PASSWORD: ZW1wX3Byb2RfcGFzc3dvcmQ=  # emp_prod_password
  REDIS_PASSWORD: ZW1wX3JlZGlzX3Bhc3N3b3Jk  # emp_redis_password
  API_KEY: ZW1wX2FwaV9rZXk=  # emp_api_key

---
# Deployment for main EMP application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-app
  namespace: emp-system
  labels:
    app: emp-app
    version: v1.1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emp-app
  template:
    metadata:
      labels:
        app: emp-app
        version: v1.1
    spec:
      containers:
      - name: emp-app
        image: emp-app:v1.1
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: EMP_ENV
          value: "production"
        - name: PYTHONPATH
          value: "/app"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: REDIS_HOST
          value: "emp-redis"
        - name: POSTGRES_HOST
          value: "emp-postgres"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: emp-data
          mountPath: /app/data
        - name: emp-logs
          mountPath: /app/logs
        - name: emp-reports
          mountPath: /app/reports
      volumes:
      - name: emp-data
        persistentVolumeClaim:
          claimName: emp-data-pvc
      - name: emp-logs
        persistentVolumeClaim:
          claimName: emp-logs-pvc
      - name: emp-reports
        persistentVolumeClaim:
          claimName: emp-reports-pvc

---
# Service for EMP application
apiVersion: v1
kind: Service
metadata:
  name: emp-app-service
  namespace: emp-system
spec:
  selector:
    app: emp-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP

---
# Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emp-ingress
  namespace: emp-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - emp.example.com
    secretName: emp-tls
  rules:
  - host: emp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emp-app-service
            port:
              number: 8000

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: emp-hpa
  namespace: emp-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emp-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
# Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emp-logs-pvc
  namespace: emp-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emp-data-pvc
  namespace: emp-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emp-reports-pvc
  namespace: emp-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd 