# EMP Redis Configuration
# Configuration for Redis-based state management

redis:
  name: "emp_state_store"
  version: "1.1.0"
  
  # Connection configuration
  connection:
    host: "localhost"
    port: 6379
    db: 0
    password: "${REDIS_PASSWORD}"
    ssl: false
    ssl_cert_reqs: "required"
    
  # Connection pool settings
  pool:
    max_connections: 20
    retry_on_timeout: true
    socket_keepalive: true
    socket_keepalive_options: {}
    
  # Key prefixes for different data types
  key_prefixes:
    population: "emp:population:"
    genome: "emp:genome:"
    strategy: "emp:strategy:"
    performance: "emp:performance:"
    risk: "emp:risk:"
    state: "emp:state:"
    events: "emp:events:"
    cache: "emp:cache:"
    
  # TTL settings (in seconds)
  ttl:
    population: 3600  # 1 hour
    genome: 86400     # 24 hours
    strategy: 86400   # 24 hours
    performance: 3600 # 1 hour
    risk: 1800        # 30 minutes
    state: 300        # 5 minutes
    events: 7200      # 2 hours
    cache: 600        # 10 minutes
    
  # Persistence settings
  persistence:
    save_interval: 300  # Save every 5 minutes
    max_memory: "2gb"
    max_memory_policy: "allkeys-lru"
    
  # Monitoring settings
  monitoring:
    enabled: true
    metrics_interval: 60  # Collect metrics every minute
    health_check_interval: 30  # Health check every 30 seconds 