# EMP Fitness Definition v1.1 - Default Configuration
# Defines fitness criteria for evolved trading strategies

fitness_definition:
  version: "1.1.0"
  name: "default_v1"
  description: "Default fitness definition for balanced risk-return optimization"
  created_at: "2024-01-01T00:00:00Z"
  author: "EMP System"
  
  # Performance Metrics Weights
  performance_weights:
    total_return: 0.25
    annualized_return: 0.20
    sharpe_ratio: 0.20
    sortino_ratio: 0.15
    win_rate: 0.10
    profit_factor: 0.10
    
  # Risk Metrics Weights
  risk_weights:
    max_drawdown: 0.30
    volatility: 0.25
    var_95: 0.20
    cvar_95: 0.15
    beta: 0.10
    
  # Thresholds for Minimum Acceptable Performance
  minimum_thresholds:
    total_return: 0.05        # 5% minimum return
    sharpe_ratio: 0.5         # 0.5 minimum Sharpe ratio
    sortino_ratio: 0.5        # 0.5 minimum Sortino ratio
    win_rate: 0.45            # 45% minimum win rate
    max_drawdown: 0.20        # 20% maximum drawdown
    volatility: 0.30          # 30% maximum volatility
    
  # Penalty Factors for Violations
  penalty_factors:
    below_minimum_return: 0.5
    below_minimum_sharpe: 0.7
    above_maximum_drawdown: 0.8
    above_maximum_volatility: 0.6
    
  # Bonus Factors for Excellence
  bonus_factors:
    high_return_bonus: 1.2    # 20% bonus for returns > 15%
    high_sharpe_bonus: 1.15   # 15% bonus for Sharpe > 1.5
    low_drawdown_bonus: 1.1   # 10% bonus for drawdown < 10%
    
  # Time-based Adjustments
  time_adjustments:
    minimum_trades: 50        # Minimum trades for valid evaluation
    minimum_days: 30          # Minimum trading days
    decay_factor: 0.95        # Decay factor for older performance
    
  # Regime-specific Adjustments
  regime_adjustments:
    bull_market_multiplier: 1.0
    bear_market_multiplier: 1.1
    sideways_market_multiplier: 1.05
    high_volatility_multiplier: 0.9
    
  # Compliance Requirements
  compliance:
    max_position_size: 0.1    # 10% maximum position size
    max_leverage: 2.0         # 2x maximum leverage
    max_correlation: 0.7      # 70% maximum correlation
    min_diversification: 3    # Minimum 3 positions
    
  # Evaluation Parameters
  evaluation:
    backtest_period: 252      # 1 year of trading days
    forward_test_period: 63   # 3 months forward testing
    confidence_interval: 0.95 # 95% confidence interval
    monte_carlo_sims: 1000    # Number of Monte Carlo simulations 