receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 256

exporters:
  logging/traces:
    loglevel: info
  logging/logs:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging/traces]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging/logs]
