version: '3.9'

x-runtime-base: &runtime-base
  build:
    context: ../..
    dockerfile: Dockerfile
    target: production
  restart: unless-stopped
  depends_on:
    timescale:
      condition: service_healthy
    redis:
      condition: service_healthy
    kafka:
      condition: service_healthy
  volumes:
    - ../../artifacts:/app/artifacts
    - ../../data:/app/data
    - ../../logs:/app/logs
  healthcheck:
    test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
    interval: 30s
    timeout: 10s
    retries: 5
    start_period: 40s
  networks:
    - emp-runtime

services:
  timescale:
    profiles: ["dev", "paper"]
    image: timescale/timescaledb:2.14.3-pg15
    container_name: emp-runtime-timescale
    environment:
      POSTGRES_DB: emp_db
      POSTGRES_USER: emp_user
      POSTGRES_PASSWORD: emp_password
      TIMESCALEDB_TELEMETRY: 'off'
    ports:
      - '5433:5432'
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "emp_user"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - emp-runtime

  redis:
    profiles: ["dev", "paper"]
    image: redis:7-alpine
    container_name: emp-runtime-redis
    command: redis-server --appendonly yes
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - emp-runtime

  kafka:
    profiles: ["dev", "paper"]
    image: bitnami/kafka:3.7
    container_name: emp-runtime-kafka
    ports:
      - '9094:9094'
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CONTROLLER://:9093,PLAINTEXT://:9092,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: CONTROLLER://emp-runtime-kafka:9093,PLAINTEXT://emp-runtime-kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@emp-runtime-kafka:9093
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_NUM_PARTITIONS: 3
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_KRAFT_CLUSTER_ID: oZ4d5P7nTbm1lYvA6w9xBg
      KAFKA_BROKER_ID: 0
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      BITNAMI_DEBUG: 'false'
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test:
        - CMD
        - /opt/bitnami/kafka/bin/kafka-topics.sh
        - --bootstrap-server
        - localhost:9092
        - --list
      interval: 15s
      timeout: 10s
      retries: 6
    networks:
      - emp-runtime

  runtime-dev:
    <<: *runtime-base
    profiles: ["dev"]
    container_name: emp-runtime-dev
    env_file:
      - env.common
      - env.dev
    ports:
      - '18080:8000'

  runtime-paper:
    <<: *runtime-base
    profiles: ["paper"]
    container_name: emp-runtime-paper
    env_file:
      - env.common
      - env.paper
    ports:
      - '18081:8000'

networks:
  emp-runtime:
    driver: bridge

volumes:
  timescale_data:
  redis_data:
  kafka_data:
