name: Python setup
description: Setup Python 3.11 with pip cache and install dev dependencies.
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip
        cache-dependency-path: requirements/dev.txt
    - name: Install dev dependencies
      shell: bash
      run: |
        set -euo pipefail
        pip install -r requirements/dev.txt
