# EMP Proving Ground v2.0 - Pilot Configuration
# Operation Phased Explosion - Phase 1: Shake-down Cruise

experiment_name: "Shake-down Cruise"

# General Pilot Configuration
population_size: 100
generations: 50
random_seed: 42
adversarial_sweep_levels: [0.3, 0.5, 0.7]

# Regime-Specific Datasets (Triathlon 1-Month Slices)
regime_datasets:
  trending:
    name: "Trending Regime"
    start_date: "2022-09-01"
    end_date: "2022-10-01"
    symbol: "EURUSD"
    description: "Clear, sustained downtrend"
    characteristics: ["high_directionality", "low_reversals", "consistent_momentum"]
  
  ranging:
    name: "Ranging Regime"
    start_date: "2021-08-01"
    end_date: "2021-09-01"
    symbol: "EURUSD"
    description: "Classic summer consolidation"
    characteristics: ["low_directionality", "high_reversals", "mean_reversion"]
  
  volatile:
    name: "Volatile/Crisis Regime"
    start_date: "2020-03-01"
    end_date: "2020-04-01"
    symbol: "EURUSD"
    description: "Peak COVID-19 market chaos"
    characteristics: ["high_volatility", "extreme_moves", "crisis_conditions"]

# HEE Hyperparameters (Pilot-Tuned)
evolution:
  elite_ratio: 0.15
  crossover_ratio: 0.60
  mutation_ratio: 0.25
  mutation_rate_per_node: 0.18
  tournament_size: 4
  max_tree_depth: 6
  complexity_penalty_lambda: 0.003
  diversity_injection_threshold: 0.25
  diversity_injection_ratio: 0.10

# Fitness Function Configuration
fitness:
  weights:
    returns: 0.25
    robustness: 0.30
    adaptability: 0.20
    efficiency: 0.15
    antifragility: 0.10
  
  # Anti-overfitting penalty
  consistency_penalty_multiplier: 0.5

# Execution Configuration
execution:
  checkpoint_interval: 10  # Save every 10 generations
  max_simulation_steps: 10000
  initial_balance: 100000.0
  base_position_size: 1000.0

# Logging Configuration
logging:
  level: "INFO"
  log_to_file: true
  log_to_console: true
  metrics_csv_interval: 1  # Log metrics every generation

# Success Criteria Thresholds
success_criteria:
  min_fitness_improvement: 0.01  # 1% minimum improvement
  trap_rate_min: 0.10  # 10% minimum
  trap_rate_max: 0.50  # 50% maximum
  max_crash_count: 0  # No crashes allowed 