from __future__ import annotations

from typing import Sequence, Any
import numpy as np
from numpy.typing import NDArray


class LedoitWolf:
    def __init__(self, **kwargs: Any) -> None: ...
    def fit(self, X: NDArray[np.float64] | Sequence[Sequence[float]]) -> LedoitWolf: ...
    def get_precision(self) -> NDArray[np.float64]: ...
    def get_covariance(self) -> NDArray[np.float64]: ...