from typing import Any

class PatternSynthesis: ...
class PatternSynthesisEngine:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def synthesize_patterns(self, price_data: Any) -> Any: ...