from typing import Any, Dict, List
import pandas as pd

class PriceActionAnalyzer:
    def update_market_data(self, df: pd.DataFrame) -> Dict[str, Any]: ...
    def _identify_support_resistance(self, df: pd.DataFrame) -> Dict[str, List[float]]: ...
    def get_price_action_score(self, df: pd.DataFrame) -> float: ...