from __future__ import annotations

from typing import Any, Dict

import pandas as pd

class PriceActionAnalyzer:
    def __init__(self) -> None: ...
    def update_market_data(self, df: pd.DataFrame) -> Dict[str, Any]: ...
    def _identify_support_resistance(self, df: pd.DataFrame) -> Dict[str, list[float]]: ...
    def get_price_action_score(self, df: pd.DataFrame) -> float: ...