from typing import Any

class InstitutionalFootprint: ...

class InstitutionalFootprintHunter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def analyze_institutional_footprint(self, price_data: Any) -> Any: ...
