# EMP Strategy Registry configuration (roadmap-aligned)
# Mirrors the SQLite-backed registry implementation in
# ``src/governance/strategy_registry.py`` and references the consolidated
# strategy catalog used by testing and governance workflows.

strategy_registry:
  name: "emp_strategy_registry"
  version: "1.2.0"
  storage:
    type: "sqlite"
    path: "artifacts/governance/strategy_registry.db"

  bootstrap:
    catalog_path: "config/trading/strategy_catalog.yaml"
    enable_catalog_sync: true
    statuses:
      default: "approved"
      experimental: "evolved"
    provenance:
      seed_source: "roadmap.phase2"
      catalogue:
        name: "emp_strategy_catalog"
        version: "2025.03"

  approval_workflow:
    stages:
      - name: "validation"
        description: "Technical validation of strategy"
        required: true
        auto_approve: false
      - name: "backtesting"
        description: "Historical performance validation"
        required: true
        auto_approve: false
      - name: "simulation"
        description: "Simulation envelope testing"
        required: true
        auto_approve: false
      - name: "human_review"
        description: "Human oversight and approval"
        required: true
        auto_approve: false
      - name: "deployment"
        description: "Live deployment approval"
        required: true
        auto_approve: false

  categories:
    trend_following:
      description: "Trend following strategies"
      risk_level: "medium"
      strategies:
        - "momentum"
        - "multi_timeframe_momentum"
    mean_reversion:
      description: "Mean reversion strategies"
      risk_level: "medium"
      strategies:
        - "mean_reversion"
    breakout:
      description: "Breakout strategies"
      risk_level: "high"
      strategies:
        - "volatility_breakout"

  risk_limits:
    trend_following:
      max_position_size: 0.10
      max_drawdown: 0.15
      max_leverage: 2.0
    mean_reversion:
      max_position_size: 0.08
      max_drawdown: 0.12
      max_leverage: 1.5
    breakout:
      max_position_size: 0.06
      max_drawdown: 0.10
      max_leverage: 1.5

  reporting:
    telemetry_channel: "telemetry.strategy.registry"
    publish_interval_seconds: 3600
    enable_uplift_reporting: true
