version: '3.9'

services:
  timescale:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: emp-timescale
    environment:
      POSTGRES_USER: emp
      POSTGRES_PASSWORD: empchangeme
      POSTGRES_DB: emp_market
      TIMESCALEDB_TELEMETRY: 'off'
    ports:
      - '5433:5432'
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "emp"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - institutional-ingest

  redis:
    image: redis:7-alpine
    container_name: emp-redis-managed
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - institutional-ingest

  kafka:
    image: bitnami/kafka:3.7
    container_name: emp-kafka
    ports:
      - '9094:9094'
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CONTROLLER://:9093,PLAINTEXT://:9092,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: CONTROLLER://emp-kafka:9093,PLAINTEXT://emp-kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@emp-kafka:9093
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CFG_NUM_PARTITIONS: 3
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_KRAFT_CLUSTER_ID: oZ4d5P7nTbm1lYvA6w9xBg
      KAFKA_BROKER_ID: 0
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      BITNAMI_DEBUG: 'false'
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test:
        - CMD
        - /opt/bitnami/kafka/bin/kafka-topics.sh
        - --bootstrap-server
        - localhost:9092
        - --list
      interval: 15s
      timeout: 10s
      retries: 6
    networks:
      - institutional-ingest

networks:
  institutional-ingest:
    driver: bridge

volumes:
  timescale_data:
  redis_data:
  kafka_data:
