from __future__ import annotations

from typing import Any

class Redis:
    def __init__(self, **kwargs: Any) -> None: ...

    def get(self, name: str) -> Any: ...

    def set(self, name: str, value: Any, **kwargs: Any) -> Any: ...

    def delete(self, *names: str) -> int: ...

    def expire(self, name: str, time: int | float) -> bool: ...

    def ping(self) -> bool: ...

    def exists(self, *names: str) -> int: ...


def from_url(url: str, **kwargs: Any) -> Redis: ...

__all__ = ["Redis", "from_url"]
