diaries_dir: artifacts/diaries
diary_glob: "diaries-*.jsonl"
redact:
  fields: ["account_id", "order_id"]
  mode: "hash"  # or "drop"
window_minutes: 1440
min_entries: 500
suggestion_cap: 10
confidence_floor: 0.65
enable_governance_gate: true
publish_channel: file://artifacts/rim_suggestions
kill_switch: false
governance:
  queue_path: artifacts/governance/reflection_queue.jsonl
  digest_path: artifacts/governance/reflection_digest.json
  markdown_path: artifacts/governance/reflection_digest.md
  auto_apply:
    enabled: true
    uplift_threshold: 0.05
    max_risk_hits: 0
    min_budget_remaining: 5.0
    max_budget_utilisation: 0.8
    require_budget_metrics: true
    default_budget_limit: 50
telemetry:
  log_dir: artifacts/rim_logs
trm_params:
  K_outer: 4
  n_inner: 3
  halt_enabled: true
