apiVersion: batch/v1
kind: CronJob
metadata:
  name: emp-nightly-replay
  namespace: emp-system
  labels:
    app: emp-app
    component: replay
spec:
  schedule: "30 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: emp-app
            component: replay
        spec:
          serviceAccountName: emp-replay-runner
          restartPolicy: OnFailure
          containers:
            - name: nightly-replay
              image: ghcr.io/emp/emp-app:latest
              imagePullPolicy: IfNotPresent
              command:
                - python3
                - tools/operations/nightly_replay_job.py
              args:
                - --log-level
                - INFO
                - --run-root
                - /app/artifacts/nightly_replay
              envFrom:
                - configMapRef:
                    name: emp-config
                - secretRef:
                    name: emp-secrets
              env:
                - name: EMP_ENV
                  valueFrom:
                    configMapKeyRef:
                      name: emp-config
                      key: EMP_ENVIRONMENT
              volumeMounts:
                - name: emp-artifacts
                  mountPath: /app/artifacts
          volumes:
            - name: emp-artifacts
              persistentVolumeClaim:
                claimName: emp-reports-pvc
