apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: emp-system
generators:
  - secret-generator.yaml
resources:
  - ../../base
patches:
  - path: patch-configmap.yaml
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
  - path: patch-cronjob.yaml
  - path: patch-scaledjob.yaml
nameSuffix: -dev
commonLabels:
  env: development
