name: CI - Type, Lint, Format

on:
  push:
    branches: ["*"]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            mypy.ini
            .pre-commit-config.yaml
            requirements/dev.txt
      - name: Cache mypy results
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ hashFiles('mypy.ini', 'pyproject.toml', 'stubs/**/*.pyi') }}
          restore-keys: |
            mypy-${{ runner.os }}-

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
      - name: mypy
        env:
          MYPYPATH: src:stubs
        run: mypy src --config-file mypy.ini
      - name: ruff
        run: ruff check .
      - name: black
        run: black --check .