name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit tests (Ubuntu, Python 3.11)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests (current scope)
        env:
          EMP_USE_MOCK_FIX: '1'
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m pytest tests/current -q

  quality:
    name: Lint/Type/Coverage (Ubuntu)
    runs-on: ubuntu-latest
    env:
      RUN_MODE: paper
      EMP_ENVIRONMENT: demo
      EMP_TIER: tier_0
      CONFIRM_LIVE: 'false'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ruff mypy pytest pytest-cov simplefix prometheus_client

      - name: Lint with ruff
        run: |
          set -euo pipefail
          ruff check . --select E9,F63,F7,F82,F401,E402,I001,F403,F405
          # Deny OpenAPI/FastAPI references in FIX-only build (code only, deterministic)
          MATCHES=$(rg -n -g '!docs/**' -g '!**/*.md' '(ctrader_open_api|CONNECTION_PROTOCOL=openapi|from\s+fastapi|import\s+fastapi|import\s+uvicorn)' -- scripts src config || true)
          if [ -n "$MATCHES" ]; then
            echo "OpenAPI/FastAPI references found in FIX-only build. Please remove them."
            echo "$MATCHES"
            exit 1
          else
            echo "No OpenAPI/FastAPI references in code."
          fi

      - name: Type check with mypy
        run: mypy --ignore-missing-imports src

      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest tests/current --cov=src --cov-report=term --cov-fail-under=70 -q

  mypy-full:
    name: Type check (full posture, warning-only)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install mypy
      - name: Run mypy (full posture)
        run: mypy src

  backtest:
    name: Offline Backtest Smoke (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Prepare fixtures
        run: |
          mkdir -p data/md_capture data/macro docs/reports/backtests
          printf '{"symbol":"EURUSD","timestamp":"2025-01-01T00:00:00","bids":[[1.1,1000000]],"asks":[[1.1002,1200000]]}\n' > data/md_capture/capture.jsonl
          printf '{"timestamp":"2025-01-01T00:30:00","event":"CPI","currency":"EUR"}\n' > data/macro/calendar.jsonl
      - name: Run backtest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python scripts/backtest_report.py --file data/md_capture/capture.jsonl --macro-file data/macro/calendar.jsonl --out-dir docs/reports/backtests
          python scripts/generate_html_report.py --csv docs/reports/backtests/why_features.csv --out docs/reports/backtests/WHY_FEATURES.html
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backtest-report
          path: docs/reports/backtests
