name: Import hygiene

on:
  pull_request:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  import-hygiene:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install optional dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --quiet PyYAML || true

      - name: Legacy import guard
        shell: bash
        run: |
          python scripts/cleanup/check_legacy_imports.py --root src --map docs/development/import_rewrite_map.yaml --fail --verbose

      - name: Import rewrite dry-run (strict)
        shell: bash
        run: |
          python scripts/cleanup/rewrite_imports.py --root src --map docs/development/import_rewrite_map.yaml --dry-run --strict --verbose