name: Replay Nightly

on:
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  issues: write

jobs:
  replay:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/python-setup

      - name: Compute timestamp (UTC)
        id: timestamp
        shell: bash
        run: |
          set -euo pipefail
          TS="$(date -u +'%Y%m%dT%H%M%SZ')"
          echo "RUN_TS=${TS}" >> "$GITHUB_ENV"

      - name: Run nightly replay harness
        id: run-replay
        shell: bash
        run: |
          set -euxo pipefail
          python3 tools/operations/nightly_replay_job.py \
            --timestamp "${{ env.RUN_TS }}" \
            --log-level INFO \
            --approvals ops \
            --approvals qa

      - name: Upload nightly replay artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-replay-${{ env.RUN_TS }}
          path: artifacts/nightly_replay/${{ env.RUN_TS }}
