# Typing Nightly workflow
name: Typing Nightly

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/python-setup

      - name: Guard: disallow [tool.mypy] in pyproject.toml
        shell: bash
        run: |
          if grep -n '^\[tool\.mypy\]' pyproject.toml >/dev/null 2>&1; then
            echo "[tool.mypy] detected in pyproject.toml; use mypy.ini as single source of truth"
            exit 1
          fi

      - name: Compute timestamp (UTC)
        id: timestamp
        shell: bash
        run: |
          set -euo pipefail
          TS="$(date -u +'%Y-%m-%dT%H-%M-%SZ')"
          echo "TS=${TS}" >> "$GITHUB_ENV"

      - name: Run mypy and capture snapshot
        shell: bash
        run: |
          set -euxo pipefail
          TS="${{ env.TS }}"
          OUT="mypy_snapshot_${TS}.txt"
          SUM="mypy_summary_${TS}.txt"
          CSV="mypy_ranked_offenders_${TS}.csv"

          ERR=0
          mypy --config-file mypy.ini |& tee "${OUT}" || ERR=$?

          TOTALS="$(grep -E 'Found [0-9]+ errors? in [0-9]+ files?' "${OUT}" || true)"
          if [ -z "${TOTALS}" ]; then
            echo "mypy completed, exit_code=${ERR}" > "${SUM}"
          else
            echo "${TOTALS}" > "${SUM}"
          fi

          echo "path,count" > "${CSV}"
          awk -F: '/\.py:[0-9]+: error:/ {print $1}' "${OUT}" \
            | sort | uniq -c | sort -rn \
            | awk '{print $2","$1}' >> "${CSV}"

          exit ${ERR}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: typing-nightly-${{ env.TS }}
          path: |
            mypy_snapshot_${{ env.TS }}*.txt
            mypy_summary_${{ env.TS }}*.txt
            mypy_ranked_offenders_${{ env.TS }}*.csv

